server:
  port: 8000

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/products/**
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/orders/**
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://discovery-server:8761/eureka
  instance:
    # hostname: localhost
    hostname: api-gateway
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0 # 모든 요청에 traceId 부여
  zipkin:
    tracing:
      # endpoint: http://localhost:9411/api/v2/spans
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'
