server:
  port: 8083

spring:
  application:
    name: user-service
  config:
    # import: optional:configserver:http://localhost:8888
    import: optional:configserver:http://config-server:8888

eureka:
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka
      defaultZone: http://discovery-server:8761/eureka
  instance:
    # hostname: localhost
    hostname: user-service
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0 # 모든 요청에 traceId 부여
  zipkin:
    tracing:
      # endpoint: http://localhost:9411/api/v2/spans
      endpoint: http://zipkin:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: '*'