server:
  port: 8082

spring:
  application:
    name: order-service
  config:
    import: optional:configserver:http://config-server:8888

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka